//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class node
    {
        public int Orderid { get; set; }
        public short CustomerName { get; set; }
        public string OrderDate { get; set; }
        public bool OrderAmount { get; set; }
    }
}
